POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username":"ze", "password":"password1234"}

###

POST http://127.0.0.1:8000/register
Content-Type: application/json

{"username":"ze", "password":"password1234", "email":"ze@sapo.pt"}

###

GET http://127.0.0.1:8000/test-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2NDY1NTIyLCJpYXQiOjE3MTY0Mjk1MjIsImp0aSI6ImQyZmQwNGQ2YmRjMDRkZjY4YTA4ZTEzNzBlYzNkNzY4IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.y7S55I_h7emWDc27kjZ8akWVaKN1TkCKkEUofC-2UJM

{}

###
GET http://127.0.0.1:8000/specialities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2NDY1NTIyLCJpYXQiOjE3MTY0Mjk1MjIsImp0aSI6ImQyZmQwNGQ2YmRjMDRkZjY4YTA4ZTEzNzBlYzNkNzY4IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.y7S55I_h7emWDc27kjZ8akWVaKN1TkCKkEUofC-2UJM

{}

###
GET http://127.0.0.1:8000/doctors/Sports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2NDY1NTIyLCJpYXQiOjE3MTY0Mjk1MjIsImp0aSI6ImQyZmQwNGQ2YmRjMDRkZjY4YTA4ZTEzNzBlYzNkNzY4IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.y7S55I_h7emWDc27kjZ8akWVaKN1TkCKkEUofC-2UJM

{}

###
POST http://127.0.0.1:8000/set_appointment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2NDY1NTIyLCJpYXQiOjE3MTY0Mjk1MjIsImp0aSI6ImQyZmQwNGQ2YmRjMDRkZjY4YTA4ZTEzNzBlYzNkNzY4IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.y7S55I_h7emWDc27kjZ8akWVaKN1TkCKkEUofC-2UJM

{
    "date": "2024-05-20",
    "hour": "14:30",
    "speciality": "Fisioterapia Respiratória",
    "doctor": "João Pratas "
}

###
POST http://127.0.0.1:8000/populate-doctors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2NDY1NTIyLCJpYXQiOjE3MTY0Mjk1MjIsImp0aSI6ImQyZmQwNGQ2YmRjMDRkZjY4YTA4ZTEzNzBlYzNkNzY4IiwidXNlcl9pZCI6MSwiaWQiOjEsInVzZXJuYW1lIjoiemUiLCJlbWFpbCI6InplQHNhcG8ucHQifQ.y7S55I_h7emWDc27kjZ8akWVaKN1TkCKkEUofC-2UJM

{}