# Generated by Django 5.0.4 on 2024-05-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_appointment_doctor_payment_user_delete_item_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="appointments",
        ),
        migrations.AddField(
            model_name="appointment",
            name="est_time",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="appointment",
            name="hour",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.user"
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="room",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
